# Generated by Django 4.0.5 on 2022-06-27 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flavours', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=250)),
                ('imageurl', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.TextField(max_length=500)),
                ('instructions', models.TextField(max_length=500)),
                ('imageurl', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('created_date', models.DateField(verbose_name='Date Added')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cake')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
