# Generated by Django 4.0.5 on 2022-06-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_recipe_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='flavours',
            field=models.CharField(choices=[('0', 'Plain Sponge'), ('1', 'Caramel'), ('2', 'Chocolate'), ('3', 'Cream Cheese'), ('4', 'Fruit'), ('5', 'Spiced'), ('6', 'Vanilla')], default='0', max_length=20),
        ),
    ]
